version: "3.7"

services:

  postgres:
    container_name: commu_postgres
    image: postgres:14.5-alpine
    env_file:
      - .env
    shm_size: 64M
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/psql_init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  django:
    container_name: commu_django
    env_file:
      - .env
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    volumes:
      # Mount the current directory into `/app` inside the running container.
      - .:/app
    restart: always
    ports:
      - "${DJANGO_PORT_ON_DOCKER_HOST:-8000}:8000"

volumes:
  postgres_data:
