[tool.poetry]
name = "lacommunaute"
version = "0.1.0"
description = "La communauté de l'inclusion"
authors = []
license = "GNU AFFERO GENERAL PUBLIC LICENSE"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.1.1"


[tool.poetry.group.dev.dependencies]
poethepoet = "^0.16.2"
black = "^22.8.0"
flake8 = "^5.0.4"
isort = "^5.10.1"
pylint = "^2.15.2"
pylint-django = "^2.5.3"
pre-commit = "^2.20.0"
djhtml = "^1.5.2"
coverage = "^6.4.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
export = { shell = "poetry export --without-hashes --output requirements/prod.txt" }
export_dev = { shell = "poetry export --without-hashes --with dev --output requirements/dev.txt" }
